# Generated by Django 4.2.3 on 2023-08-02 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('file_url', models.URLField()),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('published', 'PUBLISHED'), ('rejected', 'REJECTED')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
