# Generated by Django 4.2.3 on 2023-08-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_articlesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='file_url',
            field=models.ImageField(upload_to='articles/'),
        ),
    ]
