# Generated by Django 4.2.3 on 2023-08-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_articlesmodel_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
